[build]
  # Build command (for static sites, this can be empty)
  command = ""
  
  # Directory to publish (root directory for static HTML sites)
  publish = "."
  
  # Functions directory (if you add serverless functions later)
  functions = "netlify/functions"

[build.environment]
  # Environment variables for build process
  NODE_VERSION = "18"

# Redirect rules for SPA behavior (optional)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 404

# Headers for better performance and security
[[headers]]
  for = "/*"
  [headers.values]
    # Security headers
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # Performance headers
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Custom error pages (optional)
# [[redirects]]
#   from = "/404"
#   to = "/404.html"
#   status = 404
